---
#
# Ansible managed
#
repository:
  description: Install dependecies to support the Ansible setuptools modules.
  homepage: https://buluma.github.io/
  topics: coredependencies, ansible, molecule, tox, playbook
