---
# tasks file for setuptools

- name: Install packages
  ansible.builtin.package:
    name: "{{ setuptools }}"
    state: present
    update_cache: yes
  notify:
    - gather facts

- name: Reset connection
  ansible.builtin.meta: reset_connection

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ setuptools_pip_packages }}"
    state: present
  failed_when: no
  notify:
    - gather facts

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
